/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dutjava.tracnghiem;

import dutjava.tracnghiem.model.repository.AnswerRepository;

public class App {
    public static void main(String[] args) {
        // DBUtils.instance.SetUsernamePassword("root", "ComTMM0112");
        // DBUtils.instance.executeQuery("SELECT * FROM student");

        // System.out.println(A.class.getInterfaces()[0].getInterfaces()[0].getName());
        AnswerRepository a = new AnswerRepository();
    }
}
