/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dutjava.tracnghiem;

import java.util.List;

import dutjava.tracnghiem.container.AppHost;
import dutjava.tracnghiem.container.HostType;
import dutjava.tracnghiem.model.model.AnswerModel;
import dutjava.tracnghiem.model.model.QuestionModel;
import dutjava.tracnghiem.model.model.TestModel;
import dutjava.tracnghiem.model.service.ITestService;
import dutjava.tracnghiem.util.database.DBUtils;
import dutjava.tracnghiem.view.page.AdminPage;
import dutjava.tracnghiem.view.page.TestListPage;

public class App {
    public static void main(String[] args) {
        DBUtils.instance.SetUsernamePassword("root", "ComTMM0112");
        // DBUtils.instance.executeQuery("SELECT * FROM student");
        // System.out.println(A.class.getInterfaces()[0].getInterfaces()[0].getName());
        ITestService service = AppHost.host.get(HostType.TestService);
        // TestModel model = service.getById(2).get();
        // TestModel model = service.save(new TestModel("Test", "Test", List.of(
        // new QuestionModel("Question test 1", 10, List.of(
        // new AnswerModel("a", false),
        // new AnswerModel("b", false),
        // new AnswerModel("c", true))),
        // new QuestionModel("Question test 2", 10, List.of(
        // new AnswerModel("a", false),
        // new AnswerModel("b", false),
        // new AnswerModel("c", true))),
        // new QuestionModel("Question test 3", 10, List.of(
        // new AnswerModel("a", false),
        // new AnswerModel("b", false),
        // new AnswerModel("c", true))))))
        // .get();
        // System.out.println("Test: " + model.getName() + " - " +
        // model.getDescription());
        // System.out.println(model.getQuestions().size());
        // for (QuestionModel question : model.getQuestions()) {
        // System.out.println(question.getQuestionDescription() + ":");
        // for (AnswerModel answer : question.getAnswers())
        // System.out.println(answer.getAnswer() + " " + answer.isCorrect());
        // }

        TestListPage form = AppHost.host.get(HostType.TestListPage);
        form.lateInit();
        form.setVisible(true);

        // AdminPage form = AppHost.host.get(HostType.AdminPage);
        // form.lateInit();
        // form.setVisible(true);
    }
}
